### ISSUE TITLE
EXCEPTION: Attempt to use a dehydrated detector.

### ISSUE THREAD

**Issue by vaseker** [ceolter/ag-grid-ng2-example#1]
Hello. 
I got error `EXCEPTION: Attempt to use a dehydrated detector.` while reloading `ag-grid` component via `angular/router`.
[Here is code sample](https://github.com/vaseker/ag-grid-ng2-example/commit/aa4809f92137d9ccb6457d8fcb433a059098b232)

Have you any ideas to avoid this? 

Thanks.

**Comment by vaseker** [comment]
Update: looks like this problem related with https://github.com/ceolter/ag-grid-ng2/issues/1. This error appears in case of destroying component after router.OnDeactivate event runs.

**Comment by ceolter** [comment]
the other problem is now fixed and released. please try again.

**Comment by vaseker** [comment]
Installed fresh deps but the problem is not resolved.

**Comment by ceolter** [comment]
The original problem said the 'ngOnDestroy' method was failing because
ngOnInit was never called.

Can you confirm what the error is? Or can you demonstrate somewhere I can
observe?

On 10 February 2016 at 10:08, Dmitry Vasilyev <notifications@github.com>
wrote:

> Installed fresh deps but the problem is not resolved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-ng2-example/issues/1#issuecomment-182290398>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by vaseker** [comment]
I deployed example here: http://88.198.53.113:3001

**Comment by ceolter** [comment]
Appears to be an issue with ng2 beta3:

https://github.com/angular/angular/issues/6786


On 10 February 2016 at 10:18, Dmitry Vasilyev <notifications@github.com>
wrote:

> I deployed example here: http://88.198.53.113:3001
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-ng2-example/issues/1#issuecomment-182294863>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by mthor** [comment]
set up the grid today, and I am seeing the same issue when routing to a different page. I am using angular beta 6

**Comment by ceolter** [comment]
if someone can advise what i need to do to fix it, i can oblige. however
for now, my mind just isn't in ng2 frame of mind. i'm busy working on
reworking ag-Grid and bringing in new features.


On 16 February 2016 at 17:36, mthor <notifications@github.com> wrote:

> set up the grid today, and I am seeing the same issue when routing to a
> different page. I am using angular beta 6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-ng2-example/issues/1#issuecomment-184790623>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by mthor** [comment]
I will try to dig deeper into the solution! you have done some awesome work and look forward to new features!! 

Thanks for all the work you have done!! I think this is a great example and very easy to follow!

**Comment by ceolter** [comment]
thanks for your kind words :)

On 16 February 2016 at 17:43, mthor <notifications@github.com> wrote:

> I will try to dig deeper into the solution! you have done some awesome
> work and look forward to new features!!
>
> Thanks for all the work you have done!! I think this is a great example
> and very easy to follow!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-ng2-example/issues/1#issuecomment-184794278>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by ceolter** [comment]
maybe one day the angular 2 team will write nice code​

**Comment by laurelnaiad** [comment]
I just realized I worked around this when I saw @ceolter 's name in the angular issue.... @ceoalter -- I had borrowed your React cell rendering code vis-a-vis its cellRendererFactory.... into angular in order to do fancy rendering lacking angluar compiled templates.

... and 

```
params.api.addVirtualRowListener(
            'virtualRowRemoved', params.rowIndex, () => {
              unmountComponentAtNode(eCell)
            }
          );
```

was failing, but

```
params.api.addVirtualRowListener(
            'virtualRowRemoved', params.rowIndex, () => {
              setTimeout(() => unmountComponentAtNode(eCell), 50)
            }
          );
```

works....

**Comment by tsawan** [comment]
I've forked this repo. and added routing to reproduce this issue. 
[https://github.com/tsawan/ag-grid-ng2-example](url)

Even with angular 2 beta 8, this is not fixed yet. btw, if the grid is not bound to data (useless of course) then there is no error.

**Comment by tsawan** [comment]
just found a workaround that is working if anyone is using ag-grid.
https://github.com/ceolter/ag-grid-ng2/issues/4

**Comment by born2net** [comment]
can someone explain the "dehydrated detector" with respect to the framework? I posted on SO http://stackoverflow.com/questions/36071231/can-someone-explain-the-error-in-ng2-attempt-to-use-a-dehydrated-detector

**Comment by seanlandsman** [comment]
I believe that this issue has now been resolved - closing this
